const cards=[
  {id:'price',name:'价格 / 预算',stage:'异议处理',persona:'李妈妈，初二男孩，数学 70 多分。之前给孩子报过录播课，买完只看了两周。她下班晚，怕又花冤枉钱。',voice:'说话直接，有点犹豫，不会一次把所有顾虑说完。',goal:'识别价格背后的真实顾虑，先澄清价值与适配。',parent:'我看了一下费用，确实不便宜。之前也买过课，后面孩子就不愿意点开了。',strategy:'价值澄清法',tip:'先问孩子的具体困难和试听感受，再说明最小匹配方案。',risk:'不追问家庭预算；不承诺提分。'},
  {id:'will',name:'孩子意愿',stage:'需求诊断',persona:'周妈妈，初一女孩。孩子最近作业拖到很晚，提到补课就说“又要上课”。妈妈不想硬逼。',voice:'语气克制，会先替孩子解释，担心孩子反感。',goal:'理解抗拒原因，让家长和孩子完成低压力确认。',parent:'她前面上过一段课，后面就不太愿意听。这次我也怕她一开始答应，过两天又抵触。',strategy:'镜像共情法',tip:'区分不想学、怕跟不上和时间冲突。',risk:'不绕开孩子对家长施压。'},
  {id:'trial',name:'试听转化',stage:'需求诊断',persona:'王爸爸，工作忙，孩子五年级。他替孩子听了试听，觉得老师讲得还行，但孩子当天在上兴趣班。',voice:'回答简短、重实际，不会马上表态报名。',goal:'把模糊的试听反馈转成可验证的学情。',parent:'昨天是我听的，孩子没听到。我觉得老师讲得还可以，但也不知道他自己会不会排斥。',strategy:'体验回收法',tip:'确认谁听了、听懂什么、孩子愿不愿意再试一次。',risk:'家长满意不等于孩子愿意报名。'},
  {id:'delay',name:'犹豫拖延',stage:'异议处理',persona:'陈妈妈，初三，孩子最近月考退步。她在比较两家机构，也需要和爸爸商量。',voice:'会说“再看看”，实际在意方案是否适合和家人意见。',goal:'分清信息、孩子、预算或时间问题，约定回访。',parent:'我先再看看吧，家里也得商量一下。现在一下子做决定，我心里还没底。',strategy:'低压力推进',tip:'只追问一个阻碍，并约定明确回访时间。',risk:'禁止稀缺、倒计时、焦虑催促。'},
  {id:'fit',name:'课程匹配',stage:'方案匹配',persona:'赵妈妈，初二男孩，物理刚开始吃力，数学基础也不稳。家长只想先解决最急的问题。',voice:'关注科目、节奏和负担，不喜欢一上来推荐很多课。',goal:'厘清基础、目标与课程边界，给出最小方案。',parent:'他数学、物理都有点跟不上，但我不想一开始就报一堆课，孩子压力会更大。',strategy:'最小方案法',tip:'先拆学科困难，再说明课程覆盖与补齐路径。',risk:'不包装不覆盖的服务。'},
  {id:'time',name:'时间冲突',stage:'推进执行',persona:'孙妈妈，单亲家庭，白天上班。孩子初一，晚上有作业和篮球课，母子沟通时间很零碎。',voice:'经常隔一会儿才回，优先确认事情会不会增加执行负担。',goal:'排除真实执行障碍，确认能做到的下一步。',parent:'我白天不太方便回消息，孩子这周还有考试。不是不重视，就是怕后面跟不上节奏。',strategy:'执行障碍排除',tip:'共同确定一个小于10分钟的确认动作和时间。',risk:'不把忙碌理解为不重视。'}
];

const titles={dashboard:'数据总览',practice:'AI 陪练',history:'训练记录',copilot:'实时建议引擎',knowledge:'知识库'};
const subs={dashboard:'基于授权脱敏样本与审核卡片的团队能力概览',practice:'在安全、可评测的真实家长场景中练习判断与推进',history:'仅保存在当前浏览器，供顾问回看自己的训练与复盘',copilot:'输入当前上下文，得到阶段判断、风险提示与下一步',knowledge:'用审核后的策略卡，而不是原始通话记录支撑一线顾问'};
const isDemoMode=location.protocol==='file:'||location.hostname.endsWith('github.io');
const historyKey='advisor-practice-history-v1';
function loadHistory(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return []}}
const state={view:'dashboard',scenario:cards[0],messages:[],turn:0,live:{empathy:0,diagnosis:0,action:0,compliance:20},model:'正在检测模型服务…',modelState:'checking',sending:false,review:null,history:loadHistory(),filter:'全部'};
const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));

function app(){return `<div class="shell"><aside class="side"><div class="brand"><small>● 销冠智能体</small><h1>顾问智能工作台</h1><p>训练营顾问 AI 系统 · P0</p></div><nav class="nav">${[['dashboard','▦ 数据总览'],['practice','◉ AI 陪练'],['history','◷ 训练记录'],['copilot','⚡ 实时建议'],['knowledge','▤ 知识库']].map(([id,n])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${n}</button>`).join('')}</nav><div class="side-stats">已审核证据 <b>125 条</b><br>陪练场景 <b>6 类</b><br>策略卡片 <b>6 张</b><br>风险反例 <b>17 条</b></div></aside><main class="main"><header class="top"><div><span class="eyebrow">顾问能力中枢</span><h2>${titles[state.view]}</h2><p class="sub">${subs[state.view]}</p></div><button class="model ${state.modelState}" id="modelStatus" title="点击进行一次真实模型连通性检测">${state.model}</button></header><section id="view"></section></main></div><div class="toast" id="toast"></div>`}
function dashboard(){return `<div class="grid4">${[['授权通话记录','12,070','11,681 条可用转写'],['P0 审核样本','150','125 条知识证据'],['已发布策略卡','6','覆盖高频咨询节点'],['风险反例','17','不进入实时推荐']].map(x=>`<div class="card metric"><span>${x[0]}</span><b>${x[1]}</b><div class="up">▲ ${x[2]}</div></div>`).join('')}</div><div class="grid2"><div class="card"><h3 class="section-title">阶段能力差异</h3>${[['开场建联',78],['需求诊断',63],['痛点共鸣',51],['方案匹配',74],['异议处理',46],['推进收口',57],['跟进执行',42]].map(([n,v])=>`<div class="stage"><span>${n}</span><div class="bar ${v<55?'amber':''}"><i style="width:${v}%"></i></div><span class="right">${v}%</span></div>`).join('')}</div><div class="card"><h3 class="section-title">本周训练重点</h3><table class="table"><tr><td>价格顾虑：先诊断再报价</td><td>优先</td></tr><tr><td>“考虑一下”的真实原因</td><td>优先</td></tr><tr><td>把试听反馈转为下一步</td><td>进行中</td></tr><tr><td>风险表达纠偏</td><td>持续</td></tr></table><div class="result"><b>系统建议</b><br>当前最值得拉升的不是“话术量”，而是顾问对家长主顾虑的判断准确度与下一步任务完成率。</div></div></div>`}
function practice(){let s=state.scenario,r=readiness(),progress=trainingProgress(r);let report=state.review?`<div class="reviewReport"><b>复盘结论：${escape(state.review.summary)}</b><p><b>主要缺口：</b>${escape((state.review.missing||[]).join('；')||'无')}</p><p><b>可直接练习的下一句：</b>${escape(state.review.rewrite||'')||'请继续围绕家长的主顾虑补一个诊断问题。'}</p></div>`:'';return `<div class="practice"><section class="persona"><span class="eyebrow">训练场景</span><select class="select" id="scenario">${cards.map(c=>`<option value="${c.id}" ${c.id===s.id?'selected':''}>${c.name}</option>`).join('')}</select><h3>李妈妈</h3><p>初中家长 · 成绩中等偏下 · 对线上补习保持谨慎</p><div class="goalbox"><b>本轮唯一目标</b><br>${s.goal}</div><div class="goalbox"><b>策略提示 · ${s.strategy}</b><br>${s.tip}</div><div class="goalbox risk"><b>禁说边界</b><br>${s.risk}</div></section><section class="chat"><div class="chat-head"><b>模拟咨询</b><span class="tag">${s.stage} · 第 ${state.turn}/6 轮</span></div><div class="trainingProgress">${progress}</div><div class="messages" id="messages">${state.messages.map(m=>`<div class="msg ${m.role==='家长'?'parent':'advisor'}">${escape(m.text)}</div>`).join('')}</div><div class="compose"><textarea id="reply" placeholder="先接住担心，再补一个关键事实或约定下一步。" ${state.sending||state.review?'disabled':''}></textarea><div class="actions"><span id="readiness">${state.sending?'家长正在思考…':r.text}</span><div><button class="mutebtn ${state.turn>=3?'review-ready':''}" id="end" ${state.sending||state.turn<3||state.review?'disabled':''}>${state.review?'已完成复盘':state.turn>=3?'结束并生成复盘':'完成 3 轮后可复盘'}</button><button class="primary" id="send" ${state.sending||state.review?'disabled':''}>${state.sending?'家长思考中…':state.review?'本轮已结束':'发送回复 →'}</button></div></div></div></section><aside class="coach"><h3 class="section-title">${state.review?'本轮复盘报告':'本轮评分'} <span class="label">${state.review?'训练已结束':'实时评估'}</span></h3><div class="scoreRing">${totalScore()}</div>${[['共情承接','empathy',25],['需求诊断','diagnosis',30],['下一步推进','action',25],['合规表达','compliance',20]].map(([n,k,max])=>`<div class="scoreline"><span>${n}</span><b>${state.live[k]}/${max}</b></div>`).join('')}${report}<div class="strategies"><h3 class="section-title">${state.review?'下次练习重点':'策略提示'}</h3><div class="strategy"><span class="tag">${s.strategy}</span><br>${state.review?'先围绕一个真实顾虑追问，再给低压力、可执行的下一步。':s.tip}</div><div class="strategy"><span class="tag">结束规则</span><br>最少 3 轮，建议 3–6 轮；完成共情、诊断与下一步后，点击“结束并生成复盘”。</div></div></aside></div>`}
function copilot(){return `<div class="copilot"><span class="eyebrow">会前 / 会中 / 会后辅助</span><h3>粘贴家长最近几轮对话</h3><textarea id="context" placeholder="【家长】你们的费用我看了，感觉有点贵……&#10;【家长】孩子之前也不太愿意补课……"></textarea><div class="actions"><span>系统不会自动发送任何内容</span><button id="analyse" class="primary">生成建议 →</button></div><div class="result" id="copilotResult"><h4>等待对话上下文</h4><span class="label">将根据审核后的策略卡输出：已确认事实、主顾虑、阶段、缺口、唯一下一步与可编辑回复。</span></div></div>`}
function knowledge(){let q=state.filter;let list=q==='全部'?cards:cards.filter(c=>c.stage===q);return `<div class="knowledge"><aside class="filters">${['全部','需求诊断','方案匹配','异议处理','推进执行'].map(f=>`<button data-filter="${f}" class="${f===q?'active':''}">${f}</button>`).join('')}</aside><section class="kb-grid">${list.map(c=>`<article class="kb-card"><span class="tag">${c.stage}</span><h3>${c.name}</h3><p><b>判断：</b>${c.goal}</p><p><b>动作：</b>${c.tip}</p><p class="risk"><b>边界：</b>${c.risk}</p></article>`).join('')||'<div class="empty">该分类暂未发布策略卡</div>'}</section></div>`}
function historyView(){if(!state.history.length)return `<div class="card empty"><h3>还没有训练记录</h3><p>完成一轮正式复盘后，系统会自动保存完整对话、评分、逐句分析和范文。</p><button class="primary" data-view="practice">开始第一轮训练</button></div>`;return `<div class="historyList">${state.history.map(item=>`<article class="historyItem"><div><span class="tag">${escape(item.scenario.name)}</span><h3>${new Date(item.completedAt).toLocaleString('zh-CN',{hour12:false})}</h3><p>${escape(item.review.summary||'已完成训练复盘')}</p><span class="label">${item.turn} 轮对话 · 总分 ${item.total}/100</span></div><button class="primary" data-record="${item.id}">查看完整复盘</button></article>`).join('')}</div>`}
function render(){ $('#app').innerHTML=app();$('#view').innerHTML=({dashboard,practice,history:historyView,copilot,knowledge})[state.view]();bind();if(state.view==='practice')requestAnimationFrame(()=>{let name=$('.persona h3'),profile=$('.persona p'),messages=$('#messages');if(name)name.textContent=state.scenario.persona.split('，')[0];if(profile)profile.textContent=state.scenario.persona;if(messages)messages.scrollTop=messages.scrollHeight;renderReviewDetails()}) }
function readiness(){let a=state.messages.filter(x=>x.role==='顾问').map(x=>x.text).join('');let m=[],checks={empathy:/理解|明白|担心|不急|能理解/.test(a),diagnosis:/[？?]|吗|什么|怎么|哪/.test(a),action:/今晚|明天|时间|确认|安排|下一步|回访/.test(a)};if(state.turn<3)m.push('至少完成3轮');if(!checks.empathy)m.push('先接住担心');if(!checks.diagnosis)m.push('补诊断问题');if(!checks.action)m.push('约定下一步');let qualified=checks.empathy&&checks.diagnosis&&checks.action;return {ready:state.turn>=3,qualified,text:state.turn<3?`再完成 ${3-state.turn} 轮后可复盘`:(qualified?'训练目标已完成，可以结束并生成复盘':'可结束复盘；建议先补齐：'+m.slice(1,3).join('、')),missing:m,checks,stage:state.scenario.stage}}
function trainingProgress(r){let items=[['共情承接',r.checks.empathy],['需求诊断',r.checks.diagnosis],['下一步推进',r.checks.action]];return `<span class="progressLabel">训练进度</span>${items.map(([label,done])=>`<span class="progressItem ${done?'done':''}">${done?'✓':'○'} ${label}</span>`).join('')}<span class="progressHint">建议 3–6 轮</span>`}
function localTurnReviews(){return state.messages.filter(x=>x.role==='顾问').map((x,index)=>{let text=x.text,empathy=/理解|明白|担心|不急|能理解/.test(text),question=/[？?]|吗|什么|怎么|哪|原因|情况/.test(text),next=/今晚|明天|时间|确认|安排|下一步|回访/.test(text);let worked=[empathy?'接住了家长的担心':'',question?'提出了诊断问题':'',next?'尝试推动下一步':''].filter(Boolean).join('；')||'表达了回应意愿';let issues=[!empathy?'开头没有先承接家长对孩子和费用的担心':'',!question?'没有追问一个可判断适配度的关键信息':'',!next?'没有约定低压力、明确的下一步':''].filter(Boolean).join('；')||'表达结构完整，可再让问题更具体';return {turn:index+1,advisor:text,what_worked:worked,problem:issues,better_reply:'我理解您会担心花了钱孩子却不愿意学。方便先说说他现在最抗拒的是内容跟不上、时间安排，还是之前补课体验不好？我先据此帮您判断适不适合，再和您约个方便时间把下一步对齐。'}})}
function saveTraining(){let record={id:`training-${Date.now()}`,completedAt:new Date().toISOString(),scenario:state.scenario,messages:state.messages,turn:state.turn,live:state.live,total:totalScore(),review:state.review};state.history=[record,...state.history].slice(0,100);try{localStorage.setItem(historyKey,JSON.stringify(state.history))}catch{toast('本轮已完成，但浏览器存储空间不足，未能保存记录。')}}
function openTraining(id){let item=state.history.find(x=>x.id===id);if(!item)return;state.scenario=item.scenario;state.messages=item.messages;state.turn=item.turn;state.live=item.live;state.review=item.review;state.view='practice';render()}
function renderReviewDetails(){if(!state.review)return;if(!$('#reviewStyles')){let style=document.createElement('style');style.id='reviewStyles';style.textContent='.reviewDetails{grid-column:1/-1;margin-top:16px;padding:22px;background:#151925;border:1px solid #2a3041;border-radius:13px}.reviewDetails h3{margin:0 0 8px}.turnList{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px;margin-top:15px}.turnReview,.fullScript{background:#202538;border:1px solid #30394f;border-radius:10px;padding:14px;line-height:1.7}.turnTitle{font-weight:800;color:#bcaeff}.turnReview blockquote{margin:10px 0;padding:9px 10px;border-left:3px solid #805af4;background:#181c29;color:#dce1ec}.turnReview p{margin:8px 0}.sample{margin-top:10px;padding:10px;background:#1d3a34;border-radius:7px;color:#d4f4e8}.fullScript{margin-top:16px;border-color:#4a3a88}.fullScript p{white-space:pre-wrap;margin:0;color:#e1e5f2}';document.head.append(style)}let turns=(state.review.turns||[]).filter(x=>x&&x.advisor);if(!turns.length)turns=localTurnReviews();let content=turns.map((t,i)=>`<article class="turnReview"><div class="turnTitle">第 ${t.turn||i+1} 句顾问回复</div><blockquote>${escape(t.advisor||'')}</blockquote><p><b>做得好：</b>${escape(t.what_worked||'—')}</p><p><b>需要调整：</b>${escape(t.problem||'—')}</p><div class="sample"><b>推荐改写：</b>${escape(t.better_reply||state.review.rewrite||'')}</div></article>`).join('');let panel=document.createElement('section');panel.className='reviewDetails';panel.innerHTML=`<h3>逐句教练复盘</h3><p class="label">逐条对照你的原话，先理解问题，再用范文重练；范文仅供编辑，不应机械照抄。</p><div class="turnList">${content}</div><article class="fullScript"><h3>本场景完整话术范文</h3><p>${escape(state.review.full_script||'我理解您会担心花了钱却不适合孩子。方便先说说他目前最卡的是哪一部分吗？我先帮您判断需要确认什么；如果合适，我们再约一个您方便的时间把下一步对齐。')}</p></article>`;$('#view').append(panel)}
const totalScore=()=>Math.round(Object.values(state.live).reduce((a,b)=>a+b,0));
function assess(text){state.live.empathy=Math.min(25,state.live.empathy+(/理解|明白|担心|不急|能理解/.test(text)?9:1));state.live.diagnosis=Math.min(30,state.live.diagnosis+(/[？?]|吗|什么|怎么|哪|成绩|基础|原因/.test(text)?9:2));state.live.action=Math.min(25,state.live.action+(/今晚|明天|时间|确认|安排|下一步|回访/.test(text)?8:1));if(/保证|一定能|最后名额|赶紧报名|不报/.test(text))state.live.compliance=Math.max(0,state.live.compliance-10)}
async function api(path,payload){if(isDemoMode)throw Error('公共体验版使用本地模拟，不调用私有模型服务');let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
function fallbackParentReply(text){const all=state.messages.map(x=>x.text).join(' ');const hasQuestion=/[？?]|吗|什么|怎么|哪|原因|情况/.test(text);const hasNext=/今晚|明天|时间|确认|安排|下一步|回访/.test(text);const hasEmpathy=/理解|明白|担心|不急|能理解/.test(text);const options=hasNext?["那我们就按您说的时间先确认一下。不过您觉得孩子现在最需要解决的是哪一科？","可以，那我先和孩子聊聊，确认完再和您对一下。课程是怎么根据基础来安排的呢？","好，您先把要看的内容发我，我今晚和孩子一起看完再回复您。"]:hasQuestion?["孩子现在主要是觉得跟不上，尤其数学题一多就不想做。这个情况你们会怎么判断？","他不是完全不愿意学，就是怕又坚持不下来。您一般会先怎么帮孩子进入状态？","我最担心的是报了以后还是没人盯、孩子也不配合。这个您会先怎么确认呢？"]:hasEmpathy?["嗯，您说得有道理。不过除了安慰之外，您觉得我们第一步该先看孩子哪方面？","我理解您是在替孩子考虑。那您能不能先说说，怎么判断他到底适不适合？","那如果孩子不愿意配合，课程这边会怎么安排才不会压力更大？"]:["费用是一方面，我更想知道这件事到底适不适合孩子，不能只是报名后再试。","他现在不是不努力，就是总觉得学不会。你们会先了解哪些情况？","我也不想盲目给孩子加课，想先确认一下他目前的问题到底在哪里。"];return options.find(item=>!all.includes(item))||"您说的我听到了。不过在决定前，我还是想先弄清楚孩子现在最卡的地方和我们下一步具体怎么确认。"}
async function send(){if(state.sending)return;let el=$('#reply'),t=el.value.trim();if(!t)return;state.messages.push({role:'顾问',text:t});state.turn++;assess(t);state.sending=true;render();try{let d=await api('/api/parent-reply',{scenario:state.scenario,messages:state.messages,readiness:readiness()});state.messages.push({role:'家长',text:d.reply})}catch(e){state.messages.push({role:'家长',text:fallbackParentReply(t)});toast('本轮模型未响应，已使用场景化家长追问。')}finally{state.sending=false;render()}}
async function review(){let r=readiness();if(!r.ready){toast(`请再完成 ${3-state.turn} 轮后再复盘`);return}let transcript=state.messages.map(x=>`${x.role}：${x.text}`).join('\n');try{let d=await api('/api/coach-score',{scenario:state.scenario,transcript});state.live=d.scores||state.live;state.review={summary:d.summary||'已完成复盘，建议先补齐家长主顾虑，再推进下一步。',missing:d.missing||r.missing,rewrite:d.rewrite||'我理解您的担心，方便先确认孩子目前最困扰的问题，以及我们什么时候再用 10 分钟对齐吗？',turns:d.turns||[],full_script:d.full_script||''};toast('逐句复盘报告已生成')}catch{state.review={summary:'基础复盘已完成',missing:r.missing,rewrite:'我理解您的担心，方便先确认孩子目前最困扰的问题，以及我们什么时候再用 10 分钟对齐吗？',turns:localTurnReviews(),full_script:'我理解您会担心花了钱却不适合孩子。方便先说说他目前最卡的是哪一部分吗？我先帮您判断需要确认什么；如果合适，我们再约一个您方便的时间把下一步对齐。'};toast('已按本地规则生成逐句复盘')}saveTraining();render()}
async function analyse(){let text=$('#context').value.trim();if(!text)return toast('请先粘贴对话');$('#copilotResult').innerHTML='<h4>正在分析…</h4>';try{let d=await api('/api/copilot',{context:text});$('#copilotResult').innerHTML=`<h4>${escape(d.stage||'当前阶段')}</h4><p><b>主顾虑：</b>${escape(d.concern||'待确认')}</p><p><b>缺失信息：</b>${escape((d.missing||[]).join('；'))}</p><p><b>唯一下一步：</b>${escape(d.next||'补充关键事实')}</p><p><b>建议回复：</b>${escape(d.reply||'')}</p>`}catch(e){$('#copilotResult').innerHTML='<h4>建议：先诊断，再推进</h4><p>请先确认孩子的具体问题、家长核心顾虑及可沟通时间，再约定一个低压力下一步。</p>'}}
async function checkModel(){if(isDemoMode){toast('这是公开体验版：使用本地场景化家长模拟，未暴露任何模型密钥。');return}if(location.protocol==='file:'){state.model='文件模式：AI 不可用，请访问 localhost:8080';state.modelState='error';render();toast('请通过 http://localhost:8080 打开，不要双击 index.html。');return}state.model='正在进行真实模型检测…';state.modelState='checking';render();try{let d=await api('/api/model-test',{});state.model=`Kimi Coding 已接通 · ${d.model}`;state.modelState='ok';toast('真实模型已接通：'+d.response)}catch(e){state.model='模型未接通 · 点击重试';state.modelState='error';toast(e.message||'模型检测失败')}render()}
async function initModelStatus(){if(isDemoMode){state.model='公开体验版 · 本地模拟';state.modelState='ready';render();return}if(location.protocol==='file:'){state.model='文件模式：AI 不可用，请访问 localhost:8080';state.modelState='error';render();return}try{let r=await fetch('/api/config');let d=await r.json();if(!r.ok||!d.configured)throw Error('服务端未配置模型');state.model=`Kimi Coding 已配置 · ${d.model}（点击检测）`;state.modelState='ready'}catch{state.model='服务端不可达 · 请启动 localhost:8080';state.modelState='error'}render()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>openTraining(b.dataset.record));$('#modelStatus').onclick=checkModel;if(state.view==='practice'){$('#scenario').onchange=e=>{state.scenario=cards.find(c=>c.id===e.target.value);state.messages=[{role:'家长',text:state.scenario.parent}];state.turn=0;state.live={empathy:0,diagnosis:0,action:0,compliance:20};state.review=null;render()};$('#reply').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}};$('#send').onclick=send;$('#end').onclick=review}if(state.view==='copilot')$('#analyse').onclick=analyse;if(state.view==='knowledge')document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()})}
function toast(s){let t=$('#toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3000)}
state.messages=[{role:'家长',text:state.scenario.parent}];render();initModelStatus();
